routes/web.php
<?php

use Illuminate\Support\Facades\Route;



Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

//Route::get('lang/{language}', 'LanguageController@switchLang')->name('lang.switch');

    Route::group(['prefix' => 'administrator'], function () {


        Route::get('/login', 'Admin\LoginController@login')->name('admin.login');
        Route::post('/login', 'Admin\LoginController@postLogin')->name('admin.postLogin');

        // Password Reset Routes...

        Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
        Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
        Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
        Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

    });
Route::group(['prefix' => 'administrator', 'middleware' => ['admin']], function () {

    Route::get('/', 'Admin\HomeController@index')->name('home');
    Route::get('/home', 'Admin\HomeController@index')->name('admin.home');


    Route::resource('helpAdmin', 'Admin\HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'Admin\HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'Admin\HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'Admin\HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'Admin\UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'Admin\HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'Admin\RolesController');
    Route::post('role/delete', 'Admin\RolesController@delete')->name('role.delete');


    Route::resource('users', 'Admin\UsersController');
    Route::resource('providers_app', 'Admin\ProviderController');
    Route::post('providers_app/suspend', 'Admin\ProviderController@suspend')->name('providers_app.suspend');
    Route::post('accepted','Admin\UsersController@accpetedUser')->name('user.accepted');
    Route::post('refuseUser','Admin\UsersController@refuseUser')->name('user.refuseUser');
    Route::post('reAcceptUser','Admin\UsersController@reAcceptUser')->name('user.reAcceptUser');
    Route::post('suspendUser','Admin\UsersController@suspendUser')->name('user.suspendUser');

    Route::get('settings/aboutus', 'Admin\SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'Admin\SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/termsProvider', 'Admin\SettingsController@termsGym')->name('settings.termsGym');
    Route::get('settings/terms', 'Admin\SettingsController@terms')->name('settings.terms');
    Route::get('settings/suspendElement', 'Admin\SettingsController@suspendElement')->name('settings.suspendElement');

    Route::get('/settings/app-general-settings', 'Admin\SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'Admin\SettingsController@contactus')->name('settings.contactus');
    Route::get('settings/minutes_control', 'Admin\SettingsController@minutes_control')->name('settings.minutes_control');


    Route::post('/settings', 'Admin\SettingsController@store')->name('administrator.settings.store');

//    Route::post('contactus/reply/{id}', 'Admin\SupportsController@reply')->name('support.reply');
//    Route::get('contactus', 'Admin\SupportsController@index')->name('support.index');
//    Route::get('contactus/{id}', 'Admin\SupportsController@show')->name('support.show');
//    Route::post('support/contact/delete', 'Admin\SupportsController@delete')->name('support.contact.delete');


//    Route::resource('supports', 'Admin\SupportsController');
//    Route::post('supports/delete', 'Admin\SupportsController@delete')->name('supports.delete');

//    Route::resource('types', 'Admin\TypesSupportController');


//    Route::post('city/delete/group', 'Admin\CitiesController@groupDelete')->name('cities.group.delete');
//    Route::post('cities/delete', 'Admin\CitiesController@delete')->name('city.delete');
//    Route::resource('cities', 'Admin\CitiesController');
//    Route::post('city/suspend', 'Admin\CitiesController@suspend')->name('city.suspend');

    // -------------------------------------- categories .................
//    Route::resource('categories', 'Admin\CategoriesController');
//    Route::post('categories/delete', 'Admin\CategoriesController@delete')->name('categories.delete');
//    Route::post('categories/suspend', 'Admin\CategoriesController@suspend')->name('categories.suspend');


    Route::resource('reports', 'Admin\ReportsController');


    Route::get('/testImageView', 'Admin\UsersController@testImageView')->name('Provider.testImageView');
    Route::post('/testImage', 'Admin\UsersController@testImage')->name('Provider.testImage');


    Route::resource('banks', 'Admin\BanksController');
    Route::post('bank/suspend', 'Admin\BanksController@suspend')->name('bank.suspend');

    Route::get('bank-transfer-admin', 'Admin\BankTransferController@index')->name('bank-transfer-admin');
    Route::post('accept-transfer-admin', 'Admin\BankTransferController@accepted')->name('accept-transfer-admin');
    Route::post('refuse-transfer-admin', 'Admin\BankTransferController@refuse')->name('refuse-transfer-admin');

    Route::resource('admin_contact_us_inbox', 'Admin\ContactUsController');
    Route::get('updateIsRead', 'Admin\ContactUsController@updateIsRead')->name('admin.support.updateIsRead');
    Route::get('updateIsDeleted', 'Admin\ContactUsController@updateIsDeleted')->name('admin.support.updateIsDeleted');
    Route::get('removeAllMessages', 'Admin\ContactUsController@removeAllMessages')->name('admin.support.removeAllMessages');


    Route::resource('BankProjects', 'Admin\BankProjectsController');
    Route::post('BankProjects/accepted', 'Admin\BankProjectsController@accepted')->name('BankProjects.accepted');
    Route::post('BankProjects/refuse', 'Admin\BankProjectsController@refuse')->name('BankProjects.refuse');

    Route::resource('reports', 'Admin\ReportsController');
    Route::get('provider_data_report', 'Admin\ReportsController@gym_data')->name('provider_data_report');

    Route::post('/logout', 'Admin\LoginController@logout')->name('administrator.logout');

});



Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');



Route::get('roles', function () {

    $user = auth()->user();
//    $user->retract('admin');
    $user->assign('*');
    Bouncer::allow('*')->everything();
    $user->allow('users_manage');
});


Route::post('user/update/token', function (Illuminate\Http\Request $request) {

    $user = \App\User::whereId($request->id)->first();

    if ($request->token) {
        $data = \App\Models\Device::where('device', $request->token)->first();
        if ($data) {
            $data->user_id = $user->id;
            $data->save();
        } else {


            $data = new \App\Models\Device;
            $data->device = $request->token;
            $data->user_id = $user->id;
            $data->device_type = 'web';
            $data->save();
        }
    }

})->name('user.update.token');

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Silber\Bouncer\Database\Ability;
use Silber\Bouncer\Database\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use Validator;

class RolesController extends Controller
{
    /**
     * Display a listing of Role.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      if (!Gate::allows('roles_manage')) {
            return abort(401);
        }

        $page_title = 'إدارة الأدوار';
        $roles = Role::where('name','!=','*')->get();

        if ($request->ajax()) {
            return view('admin.roles.load', ['roles' => $roles])->render();
        }

        return view('admin.roles.index')->with(compact('roles','page_title'));

    }

 
    public function create()
    {
        if (!Gate::allows('users_manage')) {
            return abort(401);
        }
        $abilities = Ability::get();


        $abilities = $abilities->filter(function ($q) {
            return $q->name !== '*';
        });

        return view('admin.roles.create', compact('abilities'))->render();


    }

    
    public function store(Request $request)
    {
        
        //Get input ...
        $post_data=['name'=>$request->name,];
    
        //set Rules .....
        $valRules = ['name'=>'required|unique:roles,name,',];
    
        //Declare Validation message
        $valMessages = [
            'name.required'=>'إسم الدور مطلوب',
            'name.unique'=>'هذا الإسم مستخدم من قبل , حاول بإسم آخر'
        ];
    
        //validate inputs ......
        $valResult = Validator::make($post_data,$valRules,$valMessages);
        
        if($valResult->passes()) {
        
            $collection = collect($request->input('abilities'));
        
            $abilites = $collection->filter(function ($value) {
                return $value != "*";
            })->values();
        
        
            $role = Role::create($request->all());
        
            $role->allow($abilites);
        
            session()->flash('success', 'لقد تم إضافة دور جديد للمستخدمين بنجاح.');
        
            return redirect(route('roles.index'));
            
        }else{
            // Grab Messages From Validator
            $valErrors = $valResult->messages();
            // Error, Redirect To User Edit
            return redirect()->back()->withInput()
                ->withErrors($valErrors);
        }
    }

 
    public function edit($id)
    {
        if (!Gate::allows('users_manage')) {
            return abort(401);
        }
        $abilities = Ability::get();

        $abilities = $abilities->filter(function ($q) {
            return $q->name != '*';
        });


        $role = Role::findOrFail($id);

        return view('admin.roles.edit', compact('role', 'abilities'));
    }

 
    public function update(Request $request, $id)
    {
         
        if (!Gate::allows('users_manage')) {
            return abort(401);
        }
        
        $role = Role::findOrFail($id);

        $role->title = $request->name;
        $role->name =   $request->name;
//        $role->title_en = $request->title_en;
        if ($role->save()) {
            //$role->update($request->all());
            $collection = collect($request->input('abilities'));

            $abilites = $collection->filter(function ($value) {
                return $value != "*";
            })->values();
            if ($abilites->count() > 0) {

                foreach ($role->getAbilities() as $ability) {
                    $role->disallow($ability->id);
                }
                $role->allow($abilites);
            }
        }

        session()->flash('success', "لقد تم تعديل الدور  ($role->title) بنجاح");
        return redirect(route('roles.index'));
    }


   
    public function destroy($id)
    {
        if (!Gate::allows('users_manage')) {
            return abort(401);
        }
        $role = Role::findOrFail($id);
        
        if ($role->users->count() > 0) {
            return response()->json([
                'status' => false,
                'message' => 'عفواً, لا يمكنك حذف الدور نظراً لوجود مستخدمين مشتركين فيه'
            ]);
        }


        foreach ($role->getAbilities() as $ability) {
            $role->disallow($ability->id);
        }

        if ($role->delete()) {
            return response()->json([
                "status" => true,

            ]);
        }
 
    }

 
    public function delete(Request $request)
    {
        if (!Gate::allows('roles_manage')) {
            return response()->json([
                'status' => false,
                'message' => 'عفواً, ليس لديك الصلاحيات لحذف الادوار'
            ]);
        }
        $role = Role::findOrFail($request->id);
        
        if ($role->users->count() > 0) {
            return response()->json([
                'status' => false,
                'message' => 'عفواً, لا يمكنك حذف الدور نظراً لوجود مستخدمين مشتركين فيه'
            ]);
        }


        foreach ($role->getAbilities() as $ability) {
            $role->disallow($ability->id);
        }

       
        if ($role->delete()) {
            return response()->json([
                'status' => true,
                'data' => [
                    'id' => $request->id
                ],
                'message' => 'لقد تم عمليه الحذف بنجاح'
            ]);
        }


    }


    function filter(Request $request)
    {

        $name = $request->keyName;

        $page = $request->pageSize;

        ## GET ALL CATEGORIES PARENTS
        $query = Role::select();
        // $categories = Category::paginate($pageSize);


        if ($name != '') {
            $query->where('name', 'like', "%$name%");
        }

        $query->orderBy('created_at', 'DESC');
        $roles = $query->paginate(($page) ?: 10);

        if ($name != '') {
            $roles->setPath('roles?name=' . $name);
        } else {
            $roles->setPath('roles');
        }


        if ($request->ajax()) {
            return view('admin.roles.load', ['roles' => $roles])->render();
        }
        ## SHOW CATEGORIES LIST VIEW WITH SEND CATEGORIES DATA.
        return view('admin.roles.index')
            ->with(compact('users'));
    }


    /**
     * Remove User from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function groupDelete(Request $request)
    {

        if (!Gate::allows('users_manage')) {
            return abort(401);
        }

        $ids = $request->ids;
        foreach ($ids as $id) {
            $role = Role::findOrFail($id);
            $role->delete();
        }


        return response()->json([
            'status' => true,
            'data' => [
                'id' => $request->id
            ]
        ]);
    }


    /**
     * Delete all selected Role at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (!Gate::allows('users_manage')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Role::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

    /**
     *
     */


    public function companyRoles()
    {


        $agencies = Agency::get();
        $abilities = Ability::get();
        $abilities = $abilities->filter(function ($q) {
            return $q->name != '*';
        });


        return view('admin.roles.companies.index')->with(compact('abilities', 'agencies'));
    }


    public function companyRolesCreate()
    {
        $agencies = Agency::get();
        $abilities = Ability::get();
        $abilities = $abilities->filter(function ($q) {
            return $q->name != '*';
        });
        return view('admin.roles.companies.create')->with(compact('abilities', 'agencies'));
    }


    function companyRolesEdit($id)
    {
        $agency = Agency::whereId($id)->first();

        $agencies = Agency::get();


        $allAbilities = Ability::get();
        $abilities = $agency->roles;

        $allAbilities = $allAbilities->filter(function ($q) {
            return $q->name != '*';
        })->values();


        return view('admin.roles.companies.edit')->with(compact('agency', 'abilities', 'agencies', 'allAbilities'));
    }

    public function companyRolesStore(Request $request)
    {

        $agency = Agency::whereId($request->agency)->first();


        $agency->roles()->attach($request->abilities);


        session()->flash('success', 'لقد تم حفظ البيانات بنجاح.');

        return redirect(route('company.custom.roles'));


    }

    public function companyRolesUpdate(Request $request, $id)
    {
        $agency = Agency::findOrFail($id);

        if ($agency->roles()->sync($request->abilities)) {
            session()->flash('success', __('maincp.add_role_to_user'));
            return redirect(route('company.custom.roles'));
        }


    }


    public function getRolescompany(Request $request)
    {


        if ($request->type == 'sub') {

            $company = Company::whereId($request->subCompany)->first();


            if ($company) {

                $abilities = $company->abilities;
            }

            $type = $request->type;

            $html = view('admin.roles.companies.customRoles')->with(compact('abilities', 'type'))->render();


        } else {
            $abilities = DB::table('company_role')
                ->where('company_id', $request->id)->get();

            $ids = [];
            foreach ($abilities as $ability) {
                $ids[] = $ability->ability_id;
            }

            $allAbilities = Ability::get();

            $abilities = Ability::whereIn('id', $ids)->get();

resources/views/admin/roles/create.blade.php
@extends('admin.layouts.master')
@section('title','إضافة')

@section('content')
    <form method="POST" action="{{ route('roles.store')  }}" enctype="multipart/form-data" data-parsley-validate
          novalidate>
        {{ csrf_field() }}



    <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="btn-group pull-right m-t-15">


                    <a href="{{ route('roles.index') }}" type="button" class="btn btn-custom waves-effect waves-light"
                       aria-expanded="false"> مشاهدة جميع الادوار
                        <span class="m-l-5">
                        <i class="fa fa-backward"></i>
                    </span>
                    </a>


                </div>
                <h4 class="page-title">إدارة الادوار</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="card-box">



                    <h4 class="header-title m-t-0 m-b-30">إضافة دور جديد</h4>


                    <div class="col-xs-12">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="usernames">الاسم *</label>
                            <input type="text" name="name" value="{{ old('name') }}" class="form-control"
                                   required placeholder="الاسم..."
                                   data-parsley-required-message = 'هذا الحقل مطلوب'/>
                            @if($errors->has('name'))
                                <p class="help-block">
                                    {{ $errors->first('name') }}
                                </p>
                            @endif
                        </div>
                    </div>


                    <div class="form-group{{ $errors->has('roles') ? ' has-error' : '' }}">
                        <label for="passWord2">الصلاحيات *</label>
                        <select multiple="multiple" class="multi-select" id="my_multi_select1" name="abilities[]" required data-parsley-required-message = 'هذا الحقل مطلوب' data-plugin="multiselect">
                            <optgroup label="الصلاحيات">
                            @foreach($abilities as  $ability)

                                <option value="{{ $ability->name }}" {{ (collect(old('abilities'))->contains($ability->name)) ? 'selected':'' }}>
                                    @if($ability == '*')
                                        كل الصلاحيات
                                    @else {{ $ability->title }}
                                    @endif
                                </option>

                            @endforeach
                         </optgroup>
                        </select>

                        @if($errors->has('abilities'))
                            <p class="help-block"> {{ $errors->first('abilities') }}</p>
                        @endif

                    </div>


                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-primary waves-effect waves-light m-t-20" type="submit">
                            حفظ البيانات
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            إلغاء
                        </button>
                    </div>

                </div>
            </div><!-- end col -->
        </div>
        <!-- end row -->
    </form>
@endsection

@section('scripts')


    <script>

        @if(session()->has('error'))
        setTimeout(function () {
            showMessage('{{ session()->get('error') }}');
        }, 3000);
        @endif

        function showMessage(message) {

            var shortCutFunction = 'error';
            var msg = message;
            var title = 'خطأ!';
            toastr.options = {
                positionClass: 'toast-top-center',
                onclick: null,
                showMethod: 'slideDown',
                hideMethod: "slideUp",
            };
            var $toast = toastr[shortCutFunction](msg, title);
            // Wire up an event handler to a button in the toast, if it exists
            $toastlast = $toast;


        }

        //In this code, if you click on one of the option group label, all sub-options will be selected automatically.

        $("optgroup").on("click", function() {

            $(this).children("option").prop("selected", "selected");
            $(this).next().children("option").prop("selected", false);
            $(this).prev().children("option").prop("selected", false);

        });

    </script>

@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layouts.master')
@section('title','تعديل')


@section('content')
    <form method="POST" action="{{ route('roles.update', $role->id) }}" enctype="multipart/form-data"
          data-parsley-validate novalidate>

    {{ csrf_field() }}
    {{ method_field('PUT') }}

    <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="btn-group pull-right m-t-15">
                    <a href="{{ route('roles.index') }}" type="button" class="btn btn-custom waves-effect waves-light"
                       aria-expanded="false"> مشاهدة جميع الادوار
                        <span class="m-l-5">
                        <i class="fa fa-backward"></i>
                    </span>
                    </a>
                </div>
                <h4 class="page-title">إدارة الادوار</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="card-box">


                    <div id="errorsHere"></div>
                    <div class="dropdown pull-right">


                    </div>

                    <h4 class="header-title m-t-0 m-b-30">تعديل الدور</h4>


                    {{--<div class="col-xs-12">--}}
                        {{--<div class="form-group">--}}
                            {{--<label for="userName"> الاسم الظاهر*</label>--}}
                            {{--<input type="text" name="title" value="{{ $role->title or old('title') }}"--}}
                                   {{--class="form-control" required--}}
                                   {{--placeholder="الاسم الظاهر..."/>--}}
                            {{--<p class="help-block" id="error_userName"></p>--}}
                            {{--@if($errors->has('title'))--}}
                                {{--<p class="help-block">--}}
                                    {{--{{ $errors->first('title') }}--}}
                                {{--</p>--}}
                            {{--@endif--}}
                        {{--</div>--}}

                    {{--</div>--}}

                    <div class="col-xs-12">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="usernames">الاسم *</label>
                            <input type="text" name="name" value="{{ $role->name   }}" class="form-control"
                                   required placeholder="الاسم..."/>
                            @if($errors->has('name'))
                                <p class="help-block">
                                    {{ $errors->first('name') }}
                                </p>
                            @endif
                        </div>
                    </div>


                    {{-- {{ $abilities }}--}}
                    @if($role->id != 1)
                    <div class="form-group{{ $errors->has('roles') ? ' has-error' : '' }}">
                        <label for="passWord2">الصلاحيات *</label>
                        <select multiple="multiple" class="multi-select" id="my_multi_select1" name="abilities[]"
                                required
                                data-plugin="multiselect">
                            @foreach($abilities as  $ability)
                                <option value="{{ $ability->name }}"
                                        @if($role->abilities->pluck('name', 'name')) @foreach($role->abilities->pluck('name', 'name') as $bilityVal) @if($bilityVal == $ability->name) selected @endif @endforeach @endif
                                        {{-- {{ (collect(old('roles'))->contains($ability)) ? 'selected':'' }}--}}
                                >

                                    {{ $ability->title }}

                                </option>
                            @endforeach

                        </select>

                        @if($errors->has('abilities'))
                            <p class="help-block"> {{ $errors->first('abilities') }}</p>
                        @endif

                    </div>
                    @endif

                    <div class="form-group text-right m-t-20">
                        <button class="btn btn-primary waves-effect waves-light m-t-20" type="submit">
                            حفظ البيانات
                        </button>
                        <button onclick="window.history.back();return false;" type="reset"
                                class="btn btn-default waves-effect waves-light m-l-5 m-t-20">
                            إلغاء
                        </button>
                    </div>

                </div>
            </div><!-- end col -->

            {{--<div class="col-lg-4">
                <div class="card-box" style="overflow: hidden;">
                    <h4 class="header-title m-t-0 m-b-30">الصورة الشخصية</h4>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <input type="file" name="image" class="dropify" data-max-file-size="6M"/>
                        </div>
                    </div>
                </div>
            </div>--}}
        </div>
        <!-- end row -->
    </form>
@endsection