routes/web.php
<?php

use Illuminate\Support\Facades\Route;



Auth::routes();



Route::get('/', 'HomeController@index')->name('home');

//Route::get('lang/{language}', 'LanguageController@switchLang')->name('lang.switch');

    Route::group(['prefix' => 'administrator'], function () {


        Route::get('/login', 'Admin\LoginController@login')->name('admin.login');
        Route::post('/login', 'Admin\LoginController@postLogin')->name('admin.postLogin');

        // Password Reset Routes...

        Route::get('password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('administrator.password.request');
        Route::post('password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('administrator.password.email');
        Route::get('password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('administrator.password.reset.token');
        Route::post('password/reset', 'Admin\Auth\ResetPasswordController@reset');

    });
Route::group(['prefix' => 'administrator', 'middleware' => ['admin']], function () {

    Route::get('/', 'Admin\HomeController@index')->name('home');
    Route::get('/home', 'Admin\HomeController@index')->name('admin.home');


    Route::resource('helpAdmin', 'Admin\HelpAdminController');
    Route::get('helpAdmin/{id}/delete', 'Admin\HelpAdminController@delete')->name('helpAdmin.delete');
    Route::post('helpAdmin/{id}/delete', 'Admin\HelpAdminController@deleteHelpAdmin')->name('helpAdmin.message.delete');
    Route::post('helpAdmin/{id}/suspend', 'Admin\HelpAdminController@suspendHelpAdmin')->name('helpAdmin.message.suspend');
    Route::get('user/{id}/delete', 'Admin\UsersController@delete')->name('user.for.delete');
    Route::post('user/suspend', 'Admin\HelpAdminController@suspend')->name('user.suspend');
    // Roles routes ..........
    Route::resource('roles', 'Admin\RolesController');
    Route::post('role/delete', 'Admin\RolesController@delete')->name('role.delete');


    Route::resource('users', 'Admin\UsersController');
    Route::resource('providers_app', 'Admin\ProviderController');
    Route::post('providers_app/suspend', 'Admin\ProviderController@suspend')->name('providers_app.suspend');
    Route::post('accepted','Admin\UsersController@accpetedUser')->name('user.accepted');
    Route::post('refuseUser','Admin\UsersController@refuseUser')->name('user.refuseUser');
    Route::post('reAcceptUser','Admin\UsersController@reAcceptUser')->name('user.reAcceptUser');
    Route::post('suspendUser','Admin\UsersController@suspendUser')->name('user.suspendUser');

    Route::get('settings/aboutus', 'Admin\SettingsController@aboutus')->name('settings.aboutus');
    Route::get('settings/taxs', 'Admin\SettingsController@taxs')->name('settings.taxs');
    Route::get('settings/termsProvider', 'Admin\SettingsController@termsGym')->name('settings.termsGym');
    Route::get('settings/terms', 'Admin\SettingsController@terms')->name('settings.terms');
    Route::get('settings/suspendElement', 'Admin\SettingsController@suspendElement')->name('settings.suspendElement');

    Route::get('/settings/app-general-settings', 'Admin\SettingsController@appGeneralSettings')->name('settings.app.general');
    Route::get('settings/contacts', 'Admin\SettingsController@contactus')->name('settings.contactus');
    Route::get('settings/minutes_control', 'Admin\SettingsController@minutes_control')->name('settings.minutes_control');


    Route::post('/settings', 'Admin\SettingsController@store')->name('administrator.settings.store');

//    Route::post('contactus/reply/{id}', 'Admin\SupportsController@reply')->name('support.reply');
//    Route::get('contactus', 'Admin\SupportsController@index')->name('support.index');
//    Route::get('contactus/{id}', 'Admin\SupportsController@show')->name('support.show');
//    Route::post('support/contact/delete', 'Admin\SupportsController@delete')->name('support.contact.delete');


//    Route::resource('supports', 'Admin\SupportsController');
//    Route::post('supports/delete', 'Admin\SupportsController@delete')->name('supports.delete');

//    Route::resource('types', 'Admin\TypesSupportController');


//    Route::post('city/delete/group', 'Admin\CitiesController@groupDelete')->name('cities.group.delete');
//    Route::post('cities/delete', 'Admin\CitiesController@delete')->name('city.delete');
//    Route::resource('cities', 'Admin\CitiesController');
//    Route::post('city/suspend', 'Admin\CitiesController@suspend')->name('city.suspend');

    // -------------------------------------- categories .................
//    Route::resource('categories', 'Admin\CategoriesController');
//    Route::post('categories/delete', 'Admin\CategoriesController@delete')->name('categories.delete');
//    Route::post('categories/suspend', 'Admin\CategoriesController@suspend')->name('categories.suspend');


    Route::resource('reports', 'Admin\ReportsController');


    Route::get('/testImageView', 'Admin\UsersController@testImageView')->name('Provider.testImageView');
    Route::post('/testImage', 'Admin\UsersController@testImage')->name('Provider.testImage');


    Route::resource('banks', 'Admin\BanksController');
    Route::post('bank/suspend', 'Admin\BanksController@suspend')->name('bank.suspend');

    Route::get('bank-transfer-admin', 'Admin\BankTransferController@index')->name('bank-transfer-admin');
    Route::post('accept-transfer-admin', 'Admin\BankTransferController@accepted')->name('accept-transfer-admin');
    Route::post('refuse-transfer-admin', 'Admin\BankTransferController@refuse')->name('refuse-transfer-admin');

    Route::resource('admin_contact_us_inbox', 'Admin\ContactUsController');
    Route::get('updateIsRead', 'Admin\ContactUsController@updateIsRead')->name('admin.support.updateIsRead');
    Route::get('updateIsDeleted', 'Admin\ContactUsController@updateIsDeleted')->name('admin.support.updateIsDeleted');
    Route::get('removeAllMessages', 'Admin\ContactUsController@removeAllMessages')->name('admin.support.removeAllMessages');


    Route::resource('BankProjects', 'Admin\BankProjectsController');
    Route::post('BankProjects/accepted', 'Admin\BankProjectsController@accepted')->name('BankProjects.accepted');
    Route::post('BankProjects/refuse', 'Admin\BankProjectsController@refuse')->name('BankProjects.refuse');

    Route::resource('reports', 'Admin\ReportsController');
    Route::get('provider_data_report', 'Admin\ReportsController@gym_data')->name('provider_data_report');

    Route::post('/logout', 'Admin\LoginController@logout')->name('administrator.logout');

});



Route::get('/sub', function (Illuminate\Http\Request $request) {

    $cities =\App\Models\City::whereParentId($request->id)->get();

    if (!empty($cities) && count($cities) > 0){
        return response()->json( $cities);
    }else{

        return response()->json(401);
    }


})->name('getSub');



Route::get('roles', function () {

    $user = auth()->user();
//    $user->retract('admin');
    $user->assign('*');
    Bouncer::allow('*')->everything();
    $user->allow('users_manage');
});


Route::post('user/update/token', function (Illuminate\Http\Request $request) {

    $user = \App\User::whereId($request->id)->first();

    if ($request->token) {
        $data = \App\Models\Device::where('device', $request->token)->first();
        if ($data) {
            $data->user_id = $user->id;
            $data->save();
        } else {


            $data = new \App\Models\Device;
            $data->device = $request->token;
            $data->user_id = $user->id;
            $data->device_type = 'web';
            $data->save();
        }
    }

})->name('user.update.token');

resources/views/Provider/layouts/_partials/header.blade.php
<!-- Navigation Bar-->
<header id="topnav">

    <div class="topbar-main">
        <div class="container">

            <!-- LOGO -->
            <div class="topbar-left">
                {{--<a href="{{ route('admin.home') }}" class="logo" style="width: 150px;">--}}
                    {{--<img style="width: 100%" src="{{ request()->root() }}/public/assets/admin/images/logo.png"></a>--}}
            </div>
            <!-- End Logo container-->


            <div class="menu-extras">

                <ul class="nav navbar-nav navbar-right pull-right">

                    <li>
                        <!-- Notification -->
                        <div class="notification-box">
                            <ul class="list-inline m-b-0">
                                <li>
                                    <a href="javascript:void(0);" class="right-bar-toggle">
                                        <i class="zmdi zmdi-notifications-none"></i>
                                    </a>
                                    <div class="noti-dot">
                                        <span class="dot"></span>
                                        <span class="pulse"></span>
                                    </div>
                                </li>

                            </ul>
                        </div>
                        <!-- End Notification bar -->
                    </li>

                    <li class="dropdown user-box">
                        <a href="" class="dropdown-toggle waves-effect waves-light profile " data-toggle="dropdown"
                           aria-expanded="true">
                            @if(!auth()->user()->image)
                                     <img src="{{  request()->root().'/default.png'}}"
                                     alt="user-img" class="img-circle user-img">
                                @else
                                    <img src="{{ request()->root().'/'.auth()->user()->image }}"
                                     alt="user-img" class="img-circle user-img">
                                @endif

                        </a>

                        <ul class="dropdown-menu">
                            <li>
                                <a href="{{ route('gym_profile.show', auth()->user()->id)}}">
                                    <i class="ti-user m-r-5"></i>@lang('maincp.personal_page')
                                </a>
                            </li>

                             <li>
                                 <a href="{{ route('gym_profile.edit', auth()->id()) }}">
                                     <i class="ti-settings m-r-5"></i>
                                    تعديل بياناتي
                               </a>
                             <li>
                             <li>
                                 <a href="#">
                                     <i class="ti-settings m-r-5"></i>
                                     <button type="hidden"  data-toggle="modal"
                                             data-target="#myModal">                                     تغير  كلمة المرور

                                     </button>

                               </a>
                             </li>

                            <li><a href="{{ route('logout') }}"
                                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    <i class="ti-power-off m-r-5"></i>@lang('maincp.log_out')
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <div class="menu-item">
                    <!-- Mobile menu toggle-->
                    <a class="navbar-toggle">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                    <!-- End mobile menu toggle-->
                </div>
            </div>

        </div>
    </div>

    <form id="logout-form" action="{{ route('Provider.logout') }}" method="POST"
          style="display: none;">
        {{ csrf_field() }}
    </form>


    <div class="navbar-custom">
        <div class="container">
            <div id="navigation">
                <!-- Navigation Menu-->
                <ul class="navigation-menu" style="    font-size: 12px;">


                    <li>
                        <a href="{{ route('Provider.home') }}"><i class="zmdi zmdi-view-dashboard"></i>
                            <span> الرئيسية </span> </a>
                    </li>



                    <li class="has-submenu">
                        <a href="{{route('orders-projects.index')}}">
                            <i class="zmdi zmdi-square-o"></i>
                            <span>  الطلبات  </span>
                        </a>

                    </li>

                    <li class="has-submenu">
                        <a href="{{route('previous-works.index')}}" >
                            <i class="zmdi zmdi-square-o"></i>
                            <span>سابقة الأعمال</span>
                        </a>
                    </li>

                    <li class="has-submenu">
                        <a href="{{ route('information_admin') }}">
                            <i class="fa fa-info"></i>
                            <span>  المعلومات الخاصة بالتطبيق       </span>
                        </a>
                    </li>
                    <li class="has-submenu">
                        <a href="{{ route('contact_us_inbox.index') }}">
                            <i class="zmdi zmdi-email"></i>
                            <span>  البريد الإلكتروني       </span>
                        </a>
                    </li>

                </ul>
                <!-- End navigation menu  -->
            </div>
        </div>
    </div>

</header>
<!-- End Navigation Bar-->


<div class="wrapper">
    <div class="container">
        <!-- Modal -->
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title"> تغير كلمة المرور</h4>
                    </div>
                    <form   id="changePass"  method="POST" action="{{route('Provider.changePassword')}}" >
                        {{ csrf_field() }}
                        <div class="modal-body">
                            <label for="current_password" class="control-label"> كلمة المرور الحالية  </label>
                            <div class="controls">
                                <input class="form-control" required data-parsley-required-message="من فضلك اكتب الباسورد القديم لديك " type="password" name="oldPassword"><br>
                            </div>
                            <label for="new_password" class="control-label">  كلمة المرور الجديدة</label>
                            <div class="controls">
                                <input  class="form-control" type="password"
                                        data-parsley-required-message="من فضلك اكتب كلمة المرور الجديدة " required
                                        id="password" name="newPassword"
                                        data-parsley-maxlength="20"
                                        data-parsley-minlength="5"
                                        data-parsley-maxlength-message=" أقصى عدد الحروف المسموح بها هى (20) حرف"
                                        data-parsley-minlength-message=" أقل عدد الحروف المسموح بها هى (5) حرف"
                                ><br>
                            </div>
                            <label for="confirm_password" class="control-label">  تأكيد كلمة المرور الجديدة</label>
                            <div class="controls">
                                <input class="form-control" type="password"
                                       required data-parsley-required-message="من فضلك اكتب تاكيد كلمة المرور "
                                       id="password-verify" name="sameNewPassword"
                                       data-parsley-equalto="#password"
                                       data-parsley-equalto-message =' غير مطابقة لكلمة المرور الجديدة'
                                       data-parsley-maxlength="20"
                                       data-parsley-minlength="5"
                                       data-parsley-maxlength-message=" أقصى عدد الحروف المسموح بها هى (20) حرف"
                                       data-parsley-minlength-message=" أقل عدد الحروف المسموح بها هى (5) حرف"
                                >
                            </div>

                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-default"  >تغير</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal"> إلغاء</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>

resources/views/Provider/layouts/_partials/scripts.blade.php
<!-- jQuery  -->
<script src="{{ request()->root() }}/public/assets/admin/js/jquery.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/bootstrap-rtl.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/detect.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/fastclick.js"></script>

<script src="{{ request()->root() }}/public/assets/admin/js/jquery.slimscroll.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/jquery.blockUI.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/waves.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/wow.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/jquery.nicescroll.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/jquery.scrollTo.min.js"></script>

<!-- KNOB JS -->
<!--[if IE]>
<script type="text/javascript"
        src="{{ request()->root() }}/public/assets/admin/plugins/jquery-knob/excanvas.js"></script>
<![endif]-->
<script src="{{ request()->root() }}/public/assets/admin/plugins/jquery-knob/jquery.knob.js"></script>


<!-- responsive-table-->
<script src="{{ request()->root() }}/public/assets/admin/plugins/RWD-Table-Patterns/dist/js/rwd-table.min.js"
        type="text/javascript"></script>


<!-- Dashboard init -->
<script src="{{ request()->root() }}/public/assets/admin/pages/jquery.dashboard.js"></script>


<!-- file uploads js -->
<!--<script src="{{ request()->root() }}/public/assets/admin/plugins/fileuploads/js/dropify.min.js"></script>-->
<script src="https://jeremyfagis.github.io/dropify/dist/js/dropify.js"></script>
<!-- Validation js (Parsleyjs) -->
<script type="text/javascript"
        src="{{ request()->root() }}/public/assets/admin/plugins/parsleyjs/dist/parsley.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js"></script>

<script src="{{ Request::root() }}/public/assets/admin/plugins/toastr/toastr.min.js"></script>

<script src="{{ request()->root() }}/public/assets/admin/plugins/switchery/switchery.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/waypoints/lib/jquery.waypoints.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/counterup/jquery.counterup.min.js"></script>

<script type="text/javascript"
        src="{{ request()->root() }}/public/assets/admin/plugins/multiselect/js/jquery.multi-select.js"></script>

<script src="{{ Request::root() }}/public/assets/admin/plugins/ckeditor/ckeditor.js"></script>
<script src="{{ Request::root() }}/public/assets/admin/plugins/ckeditor/samples/js/sample.js"></script>

<!-- Sweet Alert js -->
<script src="{{ request()->root() }}/public/assets/admin/plugins/bootstrap-sweetalert/sweet-alert.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/pages/jquery.sweet-alert.init.js"></script>


<!-- App js -->
<script src="{{ request()->root() }}/public/assets/admin/js/jquery.core.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/jquery.app.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/js/validate-ar.js"></script>

<!-- Datatables-->
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/dataTables.bootstrap.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/dataTables.buttons.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/buttons.bootstrap.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/jszip.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/pdfmake.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/vfs_fonts.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/buttons.html5.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/buttons.print.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/dataTables.fixedHeader.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/dataTables.keyTable.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/dataTables.responsive.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/responsive.bootstrap.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/datatables/dataTables.scroller.min.js"></script>


<!-- Datatable init js -->
<script src="{{ request()->root() }}/public/assets/admin/pages/datatables.init.js"></script>
{{--<script src="{{ request()->root() }}/public/assets/admin/js/examples.min.js"> </script>--}}

<!-- Toastr js -->
<script src="{{ request()->root() }}/public/assets/admin/plugins/toastr/toastr.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/summernote/dist/summernote.min.js"></script>

<!-- Modal-Effect -->
<script src="{{ request()->root() }}/public/assets/admin/plugins/custombox/dist/custombox.min.js"></script>
<script src="{{ request()->root() }}/public/assets/admin/plugins/custombox/dist/legacy.min.js"></script>


<script src="{{ request()->root() }}/public/assets/admin/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

<script>
    $('body').delegate('.numbersOnly', 'keyup keypress', function (event) {

        var limit = $(this).attr('data-limit');
        var message = $(this).attr('data-message');
        var field = $(this).attr('name');

        if (!limit) {
            limit = 25;
        }

        if (this.value.length > limit) {
            $(this).css({
                'border': '1px solid red',
                'font-size': '14px',
                'color': 'red'
            });

            /****Not Work yet****/

            $('.' + field).css({
                'font-size': '12px'
            });

            $('.' + field).html(message);




        } else {
            $(this).removeAttr('style');
            $('.' + field).html('');

        }


        // if (!Number(this.value)) {
        //     this.value = this.value.replace(/[^0-9\.]/g, '');
        //     event.preventDefault();
        //     return false;
        // }


        if (this.value.length > limit) {

            this.value = this.value.replace(/[^0-9\.]/g, '');
            if(!Number(this.value)){
                $('.' + field).html(message);
            }
            event.preventDefault();
            return false;
        }

        this.value = this.value.replace(/[^0-9\.]/g, '');
    });
</script>

@yield('scripts')
<script>

    // Date Picker
    //    jQuery('.datepicker').datepicker();

    //    jQuery('.datepicker-autoclose').datepicker({
    //        autoclose: true,
    //        todayHighlight: true
    //    });

    $('.datepicker').datepicker({format: 'yyyy-mm-dd',autoclose: true,todayHighlight: true});
    initSample();

    //    TableManageButtons.init();


</script>

resources/views/Provider/layouts/_partials/styles.blade.php
<!-- Custom box css -->
<link href="{{ request()->root() }}/public/assets/admin/plugins/summernote/dist/summernote.css" rel="stylesheet" />
<link href="{{ request()->root() }}/public/assets/admin/plugins/custombox/dist/custombox.min.css" rel="stylesheet">

<link href="{{ request()->root() }}/public/assets/admin/plugins/RWD-Table-Patterns/dist/css/rwd-table.min.css" rel="stylesheet"
      type="text/css" media="screen">
<!-- form Uploads -->
<link href="{{ request()->root() }}/public/assets/admin/plugins/fileuploads/css/dropify.min.css" rel="stylesheet"
      type="text/css"/>
<!-- Sweet Alert css -->
<link href="{{ request()->root() }}/public/assets/admin/plugins/bootstrap-sweetalert/sweet-alert.css" rel="stylesheet"
      type="text/css"/>

<link href="{{ request()->root() }}/public/assets/admin/plugins/multiselect/css/multi-select.css" rel="stylesheet"
      type="text/css"/>

<link href="{{ request()->root() }}/public/assets/admin/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/plugins/datatables/buttons.bootstrap.min.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/plugins/datatables/fixedHeader.bootstrap.min.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/plugins/datatables/responsive.bootstrap.min.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/plugins/datatables/scroller.bootstrap.min.css" rel="stylesheet"
      type="text/css"/>


<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/bootstrap.min.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/core.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/components.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/icons.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/pages.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/menu.css" rel="stylesheet"
      type="text/css"/>
<link href="{{ request()->root() }}/public/assets/admin/css-{{ config('app.locale') }}/responsive.css" rel="stylesheet"
      type="text/css"/>

<link href="{{ request()->root() }}/public/assets/admin/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css"
      rel="stylesheet"/>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css"/>

<link href="{{ Request::root() }}/public/assets/admin/plugins/toastr/toastr.css" rel="stylesheet" type="text/css"/>
<!-- Notification css (Toastr) -->
<link href="{{ Request::root() }}/public/assets/admin/plugins/toastr/toastr.min.css" rel="stylesheet" type="text/css"/>



{{--<link rel="stylesheet" href="{{ Request::root() }}/public/assets/admin/plugins/ckeditor/css/samples.css">--}}
<link href="{{ request()->root() }}/public/assets/admin/plugins/switchery/switchery.min.css" rel="stylesheet"/>

{{--<link href="{{ request()->root() }}/public/assets/admin/custom/css/custom.css" rel="stylesheet" type="text/css"/>--}}
{{--<link href="{{ request()->root() }}/public/assets/admin/custom/css/animate.css" rel="stylesheet" type="text/css"/>--}}
{{--<link href="{{ request()->root() }}/public/assets/admin/css/ionicons.min.css" rel="stylesheet">--}}
<link href="{{ request()->root() }}/public/assets/admin/plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css"
      rel="stylesheet">
<link href ="{{request()->root() }}/public/gym/general.css" rel="stylesheet">



<!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<!--<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>-->
<!--<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>-->
<![endif]-->